//descritption
var des_ndh = "<center><h4>Nhà Điều Hành - Đại Học Quốc Gia Hà Nội</h4></center>";
var des_sunwa = "<center><h4>Trung tâm Văn hóa ULIS – Đại Học Ngoại Ngữ</h4></center>";
var des_htnvd ="<center><h4>Hội Trường Nguyễn Văn Đạo - Đại Học Quốc Gia Hà Nội</h4></center>";
var des_b2 = "<center><h4>Giảng Đường B2 - Đại Học Ngoại Ngữ</h4></center>";
var des_g3 = "<center><h4>Giảng đường G3 - Đại Học Quốc Gia Hà Nội</h4></center>";
var des_e3 = "<center><h4>Đại Học Công Nghệ - Đại Học Quốc Gia Hà Nội</h4></center>"
            +"<p>Tầng 1"
            + "<ul>"
            +   "<li>Phòng Hành Chính: 101-102</li>"
            +   "<li>Phòng Công Tác Sinh Viên: 103-104</li>"
            + "</ul>"
            +"<p>Tầng 2"
            + "<ul>"
            +   "<li>Phòng Khoa Học Công Nghệ Và Hợp Tác Quốc Tế: 201</li>"
            +   "<li>Phòng Tổ Chức - Hành Chính: 202</li>"
            +   "<li>Phó Hiệu Trưởng: 203</li>"
            +   "<li>Phó Hiệu Trưởng: 204</li>"
            +   "<li>Hiệu Trưởng: 205</li>"
            +   "<li>Ban Thanh Tra: 207</li>"
            +   "<li>Trưởng Phòng Kế Hoạch - Tài Chính: 208</li>"
            +   "<li>Giám Đốc Trung Tâm Đảm Bảo Chất Lượng: 208A</li>"
            +   "<li>Trưởng Phòng KHCN và Hợp Tác Quốc Tế: 208B</li>"
            +   "<li>Trưởng Phòng Tổ Chức - Hành Chính: 209A</li>"
            +   "<li>Văn Phòng Đảng Ủy - Văn Phòng Công Đoàn: 209B</li>"
            +   "<li>Trưởng Phòng Đào Tạo: 209</li>"
            +   "<li>Văn Phòng dự án VNU - JAIST: 210</li>"
            +   "<li>Văn Phòng IEICE Việt Nam: 210</li>"
            +   "<li>Phòng Lễ Tân: 211</li>"
            +   "<li>Phòng Hội Thảo: 212</li>"
            +   "<li>Tổ Xe: 213</li>"
            + "</ul>"
            +"<p>Tầng 3"
            + "<ul>"
            +   "<li>Văn Phòng Khoa Công Nghệ Thông Tin: 201</li>"
            +   "<li>Chủ Nhiệm Khoa Công Nghệ Thông Tin: 202</li>"
            +   "<li>Phòng Họp: 203</li>"
            +   "<li>Phó Chủ Nhiệm Khoa Công Nghệ Thông Tin: 204</li>"
            +   "<li>Phó Chủ Nhiệm Khoa Công Nghệ Thông Tin: 205</li>"
            +   "<li>Phó Chủ Nhiệm Khoa Công Nghệ Thông Tin: 207</li>"
            +   "<li>Phòng Thí Nghiệm Tương Tác Người - Máy: 208</li>"
            +   "<li>Bộ Môn Các Hệ Thống Thông Tin: 208A</li>"
            +   "<li>Trung Tâm Công Nghệ Xuất Sắc IBM - UET: 208B</li>"
            +   "<li>Phòng Thí Nghiệm Công Nghệ Tri Thức: 209A</li>"
            +   "<li>Bộ Môn Công Nghệ Phần Mềm: 209B</li>"
            +   "<li>Bộ Môn Khoa Học Máy Tính: 209</li>"
            +   "<li>Bộ Môn Khoa Học Và Kĩ Thuật Tính Toán: 210</li>"
            +   "<li>Bộ Phận Nghiên Cứu Và Phát Triển: 210</li>"
            + "</ul>"
            +"<p>Tầng 4"
            + "<ul>"
            +   "<li>Phòng Họp: 201</li>"
            +   "<li>Phòng Thí Nghiệm Mạng & Truyền Thông Máy Tính: 202</li>"
            +   "<li>Phòng Thực Hành Máy Tính 1: 203</li>"
            +   "<li>Bộ Môn Mạng Và Truyền Thông Máy Tính: 204</li>"
            +   "<li>Trung Tâm Tích Hợp Liên Ngành Giám Sát Hiện Trường: 205</li>"
            +   "<li>Tổ Thư Ký Dự Án TRIG: 207</li>"
            +   "<li>Phòng Thí Nghiệm Các Hệ Thống Nhúng: 208</li>"
            +   "<li>Phòng Thí Nghiệm Bộ Môn Khoa Học Máy Tính: 208A</li>"
            + "</ul>"
            +"<p>Tầng 5"
            + "<ul>"
            +   "<li>Trung Tâm Tích Hợp Liên Ngành Giám Sát Hiện Trường: 201</li>"
            +   "<li>Kế Toán - Tài Vụ: 202</li>"
            +   "<li>Phòng Phó Giám Đốc: 203</li>"
            +   "<li>Phòng Quản Trị Mạng Và An Ninh Hệ Thống: 204</li>"
            +   "<li>Phòng Hành Chính - Tổng Hợp: 205</li>"
            +   "<li>Phòng Máy Chủ: 207</li>"
            +   "<li>Phòng Họp: 208</li>"
            +   "<li>Phòng Phó Giám Đốc: 208A</li>"
            + "</ul>"
            +"<p>Tầng 6"
            + "<ul>"
            +   "<li>Phòng Quản Lý Dịch Vụ: 207</li>"
            +   "<li>Phòng Thực Hành: 208</li>"
            +   "<li>Phòng Thí Nghiệm Toshiba - UET: 208A</li>"
            + "</ul>";
var des_e4 = "<center><h4>Đại Học Kinh Tế - Đại Học Quốc Gia Hà Nội</h4></center>"
            +"<p>Tầng 1"
            + "<ul>"
            +   "<li>Khoa Kinh Tế Chính Trị: 101</li>"
            +   "<li>Trung Tâm Đảm Bảo Chất Lượng: 102</li>"
            +   "<li>Trung Tâm Đào Tạo và Giáo Dục Quốc Tế (Giám Đốc): 103</li>"
            + "</ul>"
            +"<p>Tầng 3"
            + "<ul>"
            +   "<li>Phòng Chính Trị & Công Tác Sinh Viên: 301</li>"
            +   "<li>Phòng Hành Chính Tổng Hợp (BP. Văn Thư): 302</li>"
            +   "<li>Phó Đào Tạo (Trưởng Phòng): 303</li>"
            +   "<li>Phòng Đào Tạo (BP. Chính Quy): 304</li>"
            +   "<li>Khoa Kinh Tế - Phát Triển: 305</li>"
            +   "<li>Viện Quản Trị Kinh Doanh: 306</li>"
            + "</ul>"
            +"<p>Tầng 4"
            + "<ul>"
            +   "<li>Phòng Hành Chính - Tổng Hợp: 401</li>"
            +   "<li>Phòng Hành Chính - Tổng Hợp (Trưởng Phòng): 402</li>"
            +   "<li>Phó Hiệu Trưởng: 403</li>"
            +   "<li>Phòng Kế Hoạch & Tài Chính: 404</li>"
            +   "<li>Trung Tâm Hệ Thống Thông Tin KT & CL: 405</li>"
            +   "<li>Phòng Học: 406</li>"
            +   "<li>Khoa Kinh Tế & Kinh Doanh Quốc Tế: 407</li>"
            + "</ul>"
            +"<p>Tầng 5"
            + "<ul>"
            +   "<li>Phòng NCKH & HTPT: 501</li>"
            +   "<li>Phòng Tổ Chức Nhân Vụ: 502</li>"
            +   "<li>Phòng Tổ Chức Nhân Vụ (Trưởng Phòng): 503</li>"
            +   "<li>Phòng Đào Tạo (BP. Sau Đại Học): 504</li>"
            +   "<li>Phòng Đào Tạo (BP. Sau Đại Học): 505-506</li>"
            +   "<li>Phòng Học: 507</li>"
            +   "<li>Phòng Học: 508</li>"
            +   "<li>Trung Tâm Đào Tạo & GD Quốc Tế (Phòng Tự Học): 509</li>"
            +   "<li>Phòng Học: 510</li>"
            +   "<li>Phòng Học: 511</li>"
            +   "<li>Khoa Tài Chính Ngân Hàng: 512</li>"
            + "</ul>"
            +"<p>Tầng 6"
            + "<ul>"
            +   "<li>Phòng Học: 601</li>"
            +   "<li>Phó Hiệu Trưởng: 602</li>"
            +   "<li>Phó Bí Thư Đảng Ủy - CN. Khoa Kế Toán - Kiểm Toán: 603</li>"
            +   "<li>Phó Hiệu Trưởng: 604</li>"
            +   "<li>Thư Ký Hiệu Trưởng: 605</li>"
            +   "<li>Bí Thư Đảng Ủy - Hiệu Trưởng: 606</li>"
            +   "<li>Phòng Truyền Thông: 607</li>"
            + "</ul>"
            +"<p>Tầng 7"
            + "<ul>"
            +   "<li>Phòng Thanh Tra - Pháp Chế: 701</li>"
            +   "<li>Bộ Phận Truyền Thông: 702</li>"
            +   "<li>Bộ Phận Tạp Chí - Xuất Bản: 703</li>"
            +   "<li>Trung Tâm Nghiên Cứu QTKD: 704</li>"
            +   "<li>Phòng NCKH & HTPT (Trưởng Phòng): 705</li>"
            +   "<li>Khoa Kế Toán - Kiểm Toán: 706</li>"
            +   "<li>Viện Nghiên Cứu Kinh Tế - Chính Sách: 707</li>"
            +   "<li>Phòng Thể Thao: 708</li>"
            +   "<li>Phòng Hành Chính - Tổng Hợp (BP. Lễ Tân): 709</li>"
            +   "<li>Phòng Khách: 710</li>"
            + "</ul>"
            +"<p>Tầng 8"
            + "<ul>"
            +   "<li>Phòng Hội Thảo Quốc Tế: 801</li>"
            +   "<li>Nhà ăn: 802</li>"
            + "</ul>";
var des_e1 = "<center><h4>Khoa Luật - Đại Học Quốc Gia Hà Nội</h4></center>";
var des_e2 ="<center><h4>Viện Vi Sinh Vật Và Công Nghệ Sinh Học - Đại Học Quốc Gia Hà Nội</h4></center>";
var des_g7 = "<center><h4>Khoa Sau Đại Học, Đại Học Giáo Dục, Trung Tâm Đào Tạo & Bồi Dưỡng Lý Luận Chính Trị - Đại Học Quốc Gia Hà Nội</h4></center>"
            +"<p>Tầng 1"
            + "<ul>"
            +   "<li>Phòng Đào Tạo - 101</li>"
            +   "<li>Phòng Đào Tạo - 102</li>"
            +   "<li>Phòng Công Tác Học Sinh - Sinh Viên - 103</li>"
            +   "<li>Trung Tâm Nghiên Cứu Ứng Dụng Giáo Dục - 104 </li>"
            +   "<li>Trung Tâm Hợp Tác Đào Tạo & Bồi Dưỡng - 105</li>"
            +   "<li>Phòng Họp - 106</li>"
            +   "<li>Phòng Kế Hoạch - Tài Chính - 107</li>"
            + "</ul>"
            +"<p>Tầng 2"
            + "<ul>"
            +   "<li>Phòng Kế Hoạc - Tài Chính - 201</li>"
            +   "<li>Phòng Phó Hiệu Trưởng - 202</li>"
            +   "<li>Phòng Hành Chính - Tổng Hợp - 203 </li>"
            +   "<li>Phòng Hiệu Trưởng - 204, 205</li>"
            +   "<li>Phòng Hành Chính - Tổng Hợp - 206</li>"
            + "</ul>"
            +"<p>Tầng 3"
            + "<ul>"
            +   "<li>Phó Hiệu Trưởng - 301</li>"
            +   "<li>Phó Hiệu Trưởng - 302</li>"
            +   "<li>Phòng Khoa Học Và Quan Hệ Quốc Tế - 303</li>"
            +   "<li>Phòng Tổ Chức - Cán Bộ - 304</li>"
            +   "<li>Phòng Tổ Chức - Cán Bộ - 305</li>"
            +   "<li>Chủ Tịch Hội Đồng Khoa Học & Đào Tạo - 306</li>"
            +   "<li>Phòng Giáo Sư   - 307</li>"
            + "</ul>"
            +"<p>Tầng 4"
            + "<ul>"
            +   "<li>Phòng Họp - 401</li>"
            + "</ul>"
            +"<p>Tầng 6"
            + "<ul>"
            +   "<li>Khoa Quản Lý Giáo Dục - 604</li>"
            +   "<li>Khoa Quản Lý Giáo Dục - 605</li>"
            +   "<li>Phòng Máy Chủ - 606</li>"
            + "</ul>";
var des_b3 = "<center><h4>Khoa Sau Đại Học - Đại Học Ngoại Ngữ</h4></center>"
            +"<p>Tầng 1"
            + "<ul>"
            +   "<li>Giảng Đường - 101</li>"
            +   "<li>Phòng Thông Tin Thư Viện SĐH - 102</li>"
            +   "<li>Phòng Giảng Viên - 103</li>"
            +   "<li>Phòng Học - 104-105-106</li>"
            + "</ul>"
            +"<p>Tầng 2, Tầng 3, Tầng 4, Tầng 5, Tầng 6 chứa cac phòng họp dành cho sinh viên";
var des_g2 = "<center><h4>Giảng Đường G2 - Đại Học Công Nghệ</h4></center>";
var des_c1t = "<center><h4>Thư Viện ĐHQGHN - Đại Học Quốc Gia Hà Nội</h4></center>"
            +"<p>Tầng 1"
            + "<ul>"
            +   "<li>Phòng Phân Loại - Biên Mục</li>"
            +   "<li>Phòng Bổ Sung - Trao Đổi</li>"
            + "</ul>"
            +"<p>Tầng 2"
            + "<ul>"
            +   "<li>Phòng Đọc Tạp Chí - Luận Văn - Luận Án</li>"
            + "</ul>"
            +"<p>Tầng 3"
            + "<ul>"
            +   "<li>Trung Tâm Khảo Thí - Đại Học Quốc Gia Hà Nội</li>"
            + "</ul>"
            +"<p>Tầng 4"
            + "<ul>"
            +   "<li>Phòng Đọc Sách Tổng Hợp</li>"
            +   "<li>Phòng Phát Triển Tài Nguyên Số</li>"
            + "</ul>"
            +"<p>Tầng 5"
            + "<ul>"
            +   "<li>Phòng Đọc Chuyên Sâu Luật Kinh Tế</li>"
            +   "<li>Phòng Mượn Giáo Trình</li>"
            + "</ul>"
            +"<p>Tầng 6"
            + "<ul>"
            +   "<li>Ban Giám Đốc</li>"
            +   "<li>Khối Chức Năng</li>"
            +   "<li>Khối Nghiệp Vụ</li>"
            + "</ul>"
            +"<p>Tầng 7"
            + "<ul>"
            +   "<li>Viện Đảm Bảo Chất Lượng Giáo Dục</li>"
            +   "<li>Tạp Chí Khoa Học</li>"
            +   "<li>Trung Tâm Kiểm Định Chất Lượng Giáo Dục</li>"
            +   "<li>Trung Tâm Khảo Thí ĐHQGHN</li>"
            + "</ul>"
            +"<p>Tầng 8"
            + "<ul>"
            +   "<li>Viện Trần Nhân Tông</li>"
            +   "<li>Trung Tâm Khảo Thí ĐHQGHN</li>"
            +   "<li>Trung Tâm Hỗ Trợ Nghiên Cứu Châu Á</li>"
            + "</ul>";
var des_a2 = "<center><h4>Giảng Đường A2, Trung tâm thư viện Ngoại ngữ - Đại Học Ngoại Ngữ</h4></center>";
var des_a1 = "<center><h4>Khu hiệu bộ Đại học Ngoại ngữ - Đại Học Ngoại Ngữ</h4></center>"
            +"<p>Tầng 1"
            + "<ul>"
            +   "<li>Phòng Hành Chính Tổng Hợp: 101-102-103-104</li>"
            +   "<li>Phòng Đào Tạo: 105-107-108-109</li>"
            +   "<li>Phòng CT & CT HSSV: 106-110</li>"
            + "</ul>"
            +"<p>Tầng 2"
            + "<ul>"
            +   "<li>Ban Giám Hiệu: 206-207-209-210</li>"
            +   "<li>Phòng Thư Ký Hiệu Trưởng: 208</li>"
            +   "<li>Phòng Họp: 201-208A</li>"
            +   "<li>Phòng Kế Hoạch Tài Chính: 202-203-204-205</li>"
            + "</ul>"
            +"<p>Tầng 3"
            + "<ul>"
            +   "<li>Phòng Họp: 301</li>"
            +   "<li>Phòng Tổ Chức Cán Bộ: 302-303</li>"
            +   "<li>Phòng CT & CT HSSV: 304</li>"
            +   "<li>Khoa Đào Tạo và Bồi Dưỡng NN: 305-306-307-309</li>"
            +   "<li>Phòng Khoa Học và Công Nghệ: 310-311-312</li>"
            + "</ul>"
            +"<p>Tầng 4"
            + "<ul>"
            +   "<li>Phòng Họp: 401-406-410</li>"
            +   "<li>TT Nghiên Cứu và GDNN & Đảm Bảo Chất Lượng: 402A-B, 403-404</li>"
            +   "<li>Phòng Hợp Tác & Phát Triển: 405-407-408-409</li>"
            + "</ul>"
            +"<p>Tầng 5"
            + "<ul>"
            +   "<li>Phòng Thanh Tra và Pháp Chế: 501-511</li>"
            +   "<li>Bộ Môn Ngôn Ngữ & Văn Hóa Ả-rập: 503-504</li>"
            +   "<li>Bộ Môn Tâm Lý Giáo Dục: 506-507</li>"
            +   "<li>Bộ Môn Ngôn Ngữ & Văn Hóa Việt Nam: 508</li>"
            +   "<li>Hội Trường: 509</li>"
            +   "<li>Hội Đồng Khoa Học & Đào Tạo: 510A</li>"
            +   "<li>Hội Đồng Tư Vấn Hợp Tác Phát Triển: 510B</li>"
            +   "<li>VP Đản Ủy Công Đoàn: 505</li>"
            + "</ul>"
            +"<p>Tầng 6"
            + "<ul>"
            +   "<li>Trung Tâm Khảo Thí: 603-604-605</li>"
            + "</ul>"
            +"<p>Tầng 7"
            + "<ul>"
            +   "<li>Khu Vực Lưu Trữ</li>"
            + "</ul>";
var des_a3 = "<center><h4><p>Khoa Sau Đại học - Đại Học Ngoại Ngữ</p><p>Khoa Ngôn ngữ và Văn hoá Hàn Quốc - Đại Học Ngoại Ngữ</p><p>Trung tâm đào tạo và bồi dưỡng giáo viên - - Đại Học Ngoại Ngữ</p><p>Trung tâm Hàn Ngữ Sejong - Đại Học Ngoại Ngữ</p></h4></center>";
var des_a4 = "<center><h4><p>Trung tâm Giáo dục Quốc tế - Đại Học Ngoại Ngữ <p>Khoa Ngôn ngữ và Văn hoá Phương Đông - Đại Học Ngoại Ngữ <p>Khoa Ngôn ngữ và Văn hoá Phương Tây - Đại Học Ngoại Ngữ <p>Trung tâm Thông tin Giáo dục Đài Loan - Đại Học Ngoại Ngữ <p>Trung tâm Khảo thí Cambridge - Đại Học Ngoại Ngữ</h4></center>";
var des_a5 = "<center><h4>Nhà khách Đại học Ngoại ngữ, Khu nhà ở dành cho giảng viên quốc tế</h4></center>";
var des_cnn = "<center><h4>THPT Chuyên Ngoại Ngữ - Đại Học Ngoại Ngữ</h4></center>";
var des_ntc = "<center><h4>Nhà Thể Chất - Đại Học Quốc Gia</h4></center>";
var des_kyd = "<center><h4>Khoa Y Dược - Đại Học Quốc Gia Hà Nội</h4></center>";
var des_ktx = "<center><h4>Kí Túc Xá Ngoại Ngữ (gồm 3 dãy nhà A, B và C), Nhà ăn Sinh viên</h4></center>";
var des_ktxA = "<center><h4>Nhà A - Kí túc xá Đại Học Ngoại Ngữ</h4></center>";
var des_ktxB = "<center><h4>Nhà A - Kí túc xá Đại Học Ngoại Ngữ</h4></center>";
var des_ktxC = "<center><h4>Nhà A - Kí túc xá Đại Học Ngoại Ngữ</h4></center>";
var des_shb = "<center><h4>Khoa Quản Trị Và Kinh Doanh - Đại Học Quốc Gia Hà Nội</h4></center>";
var des_g8 = "<center><h4>Khoa Quốc Tế, TT Phát Triển Hệ Thống - Đại Học Quốc Gia Hà Nội</h4></center>";
var des_gd2 = "<center><h4>Giảng Đường GD2 - Đại Học Công Nghệ</h4></center>";
var des_c1 = "<center><h4>Giảng Đường C1 Khoa Pháp - Đại Học Ngoại Ngữ</h4></center>";
var des_c2 = "<center><h4>Khu giảng đường chất lượng cao Khoa Pháp - Đại Học Ngoại Ngữ</h4></center>";
var des_c3 = "<center><h4><p>Thư viện Khoa Pháp - Đại Học Ngoại Ngữ"
             + "<p>Phòng hội thảo - Đại Học Ngoại Ngữ"
             + "<p>Khu phòng học Sinh viên Quốc tế (SYA) - Đại Học Ngoại Ngữ</h4></center>";
var des_c4 = "<center><h4><p>Văn phòng - Đại Học Ngoại Ngữ" 
             + "Giáo vụ Khoa Ngôn ngữ và Văn hoá Pháp - Đại Học Ngoại Ngữ</h4></center>";
var des_c5 = "<center><h4><p>Trường quay, Trung tâm Multimedia - Đại Học Ngoại Ngữ"
             +  "<p>Trung tâm ứng dụng Công nghệ Thông tin vào giảng dạy Ngoại ngữ - ĐHNN</h4></center>";
var des_c6 = "<center><h4>Hội trường Vũ Đình Liên - Đại Học Ngoại Ngữ</h4></center>";
var des_g5 = "<center><h4>Trung Tâm Phát Triển ĐHQGHN - Đại Học Quốc Gia Hà Nội</h4></center>";